server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: slovakia
    url: jdbc:postgresql://localhost:5432/store
  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
  session:
    jdbc:
      initialize-schema: always
  jpa:
    open-in-view: false
jwtSecret: olena.olena
jwtExpiration: 86400



banner:
  image:
    invert: true



