server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: slovakia
    url: jdbc:postgresql://localhost:5432/store
  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?

jwtSecret: olena.olena
jwtExpiration: 86400



jpa:
  open-in-view: false

banner:
  image:
    invert: true



