server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: slovakia
    url: jdbc:postgresql://localhost:5432/store

  jpa:
    open-in-view: false

  banner:
    image:
      invert: true



